### ISSUE TITLE
[Suggestion] Separate logic into Library/DLL for external referencing

### ISSUE THREAD

**Issue by qJake** [reality-boy/miniMover#2]
Hey! This is a cool project and I have a da Vinci Pro 1.0. I'd love to be able to monitor my printing from my PC. I'm primarily a C# developer so as of right now, I don't have a way to consume your project and put a pretty WPF interface around it. I'd love to extend your work and create a really slick monitoring UI for anyone who's interested.

C# is capable of invoking unmanaged library code as long as the entry points are clearly defined.

Would you be able to separate out, or create a precompiled DLL with all of the monitoring logic in it so that I could pull it into a C# project?

I'd obviously post that code to GitHub as well!

**Comment by reality-boy** [comment]
I don't have the time right now to do it myself. but the XYZv3.cpp file is very clean, it would not be too hard for you to wrap it into a dll.  Alternatively you can look in the XYZv3.cpp file and work out the protocol for yourself and rewrite it in managed code.  It is relatively straight forward and 90% of it is just pushing strings over a serial port.  The only tricky part is working out how to encode a .3w file, if you want to support sending files to the printer remotely.

**Comment by qJake** [comment]
I'm just looking to monitor it at this point. I'm not really good with C++, but I may give it a try (and still cite your repo as a source/reference).

Thanks for the help!
