### ISSUE TITLE
SD Card Error

### ISSUE THREAD

**Issue by zombiestruck** [reality-boy/miniMover#3]
### Expected Behavior

Transfer file and start print

### Actual Behavior

Transfers, then gives an error on the machine stating SD Card Error. In the miniMover GUI it says Error: (0x0000020c) L_ERROR_SD_CARD

### Steps to reproduce

Transfer a 3w via the GUI to a DaVinci Jr 2.0 Mix.

### Machine model
DaVinci Jr 2.0 Mix

**Comment by reality-boy** [comment]
Are you able to print via XYZWare?  This error is relatively straight forward, it says the SD card built into the printer is malfunctioning and may need to be formatted and/or reinserted.  I believe on this printer the SD card is removable, although it may not be easy to gain access to it.  On my MiniMaker the SD card is hard wired to the motherboard and can not be removed.

If you can't fix this then let me know, I can try changing a flag when printing that directs the printer to save the file to the SD card. I don't believe that will fix the problem but it may be worth trying it out.

**Comment by zombiestruck** [comment]
XYZWare prints. The SD Card on my printer is easy to remove and swap.

**Comment by reality-boy** [comment]
Well that is good for you.  I will try to get you a fresh build tomorrow that turns off the SD flag when printing.

**Comment by zombiestruck** [comment]
Alright, also my printer just got a driver update and it now finally supports gcode.
Simplify3d here we come :D

**Comment by zombiestruck** [comment]
I'd just like to say: I moved away from DaVinci 3dprinters, and I am so much happier now. Their software sucks. I purchased the dremel ideabuilder 3D40 from amazon and am doing the financing plan on it. Well worth it.
