### ISSUE TITLE
da Vinci Mini Linux status output very broken

### ISSUE THREAD

**Issue by Xenolphthalein** [reality-boy/miniMover#5]
### Expected Behavior
Good Output like the following (one out of 10tries):
```
Printer Status

Bed temperature: 20 C, target temp: 0 C
Bed calibration:
 387, 391, 383
 388, 400, 385
 387, 395, 379
Printer status: 66 % 418 m 215 m
Serial number: 3j:9505,005,0
Status: (9505, 0) printing in progress
language: de
printer name: 3D
Package size: 8192 bytes
ot: 1 bytes
oc: 1 bytes
Auto level: disabled
Model number: REDACTED
Buzzer: disabled
Fd: 0
Fm: 0
Extruder temp: 0 C, target temp: 0 C
Firmware version: 14
Filament SN: 
Filament length: 0.000 m
PLA filament: 0
Z-Offset: 0
Lifetime power on time: 471960 min
Last print time: 3 min
Extruder total time: 6310 min
v string: 5.0.2,"MACrssiVa"0",""0","Mlue":"0",""0","MiValuiValue":"0","M0","MAC":"REDACTED"}}
Wireless SSID: ,"MAC":"REDACTED"}}
Wireless BSSID: 
Wireless Channel: 
Wireless RssiValue: 
Wireless PHY: 
Wireless Security: 
nozzle: 0.40 laser 0 mm sn: GB-0002-0000-TH-67R-0199-14700
File id: REDACTED
Machine serial number: REDACTED
Machine screen name: da Vinci mini w
isV5: 0, isZip: 0, comV3: 1
Printer build volume: 150 L 150 W 150 H
run took 0.0944 seconds
```
### Actual Behavior
Almost every run of the command line application looks similiar to this:
```
XYZV3::parseStatusSubstring invalid input..
Stream::clear leftover data: $}
6:7a:69"}}
$}
6:7a:69"}}
$}
$
7a:69"}}
$}
$
7a:69"}}
$}
$
7a:69"}}
$}
$
7a:69"}}
$}
$
}}
$}
$
$}
$
:69"}}
$}
6:7a:69"}}
$}
6:7a:69"}}
$}
$
7a:69"}}
$}
$
7a:69"}}
$}
$
7a:69"}}
$}
$

$

XYZV3::parseStatusSubstring invalid input.
XYZV3::modelToInfo model number not found 'dv1MW'
XYZV3::parseStatusSubstring invalid input
XYZV3::modelToInfo model number not found 'dv1MW0A00AMW0A000'
XYZV3::parseStatusSubstring invalid input..run took 0.0910 seconds

hit any key to continue.
```
[debug.txt](https://github.com/reality-boy/miniMover/files/2431925/debug.txt)

### Steps to reproduce
I can replicate this error on my local machine infinite times.
Side Note: The Autodetect feature detects always the ttyS10, but it is in fact ttyACM0. I start the application like this: 
```./minimover -d /dev/ttyACM0 -s```

### Machine model
da Vinci Mini w

**Comment by Xenolphthalein** [comment]
Note: i compiled a fresh copy of minimover from the current git source.

**Comment by reality-boy** [comment]
Thanks for that, I was able to reproduce the bug here.  I will try to get
it fixed right away.

In the meantime consider pulling version 0.9, it should be stable.

**Comment by reality-boy** [comment]
Ok, I have a fix for the main issue. I was assuming that memcpy() would always be safe for in place copying of a string, but apparently on linux that is not the case.  Now I shift my strings down by hand and everything is better.  Really I should be using a circular queue, but I'll save that for another day.  Just pull head and it should all work for you now.

Anyway I will see what I can do to improve auto detecting the serial port.  On windows I can scan the device names for XYZWare to find the printer, on linux I'm just latching onto the first available serial port.  I have not found a clean way to get the actual device name (the 'pretty name'), at least not one that works on the linux emulator I'm running on windows.

**Comment by NikikiN** [comment]
hello, i need bump for Da Vinci mini w 1.2.3-1.2.5 firmware to SAM-BA. PLZ help
